name: Purge Cache

on:
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Send Purge Request
        run: cd .github/scripts/ && yarn && node purge-cache.js
